version: "3.0"

services:
  dst:
    image: ubuntu:22.04
    container_name: dst
    hostname: dst-host
    volumes:
      - ./docker/server:/root/Server
      - ./docker/worlds:/root/Klei
      - ./build:/root/build
    tty: true
    # environment:
    #   - TEST_ENV=hello
    # ports:
    #   - 5000:80
    # networks:
    #  - frontend
    # depends_on:
    #   - redis

